#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Registre el cargador automático
| ------------------------------------------------- -------------------------
|
| Composer proporciona un cargador de clases conveniente y generado automáticamente
| para nuestra aplicación. ¡Solo necesitamos utilizarlo! Lo necesitaremos
| en el guión aquí para que no tengamos que preocuparnos por el
| cargando cualquiera de nuestras clases "manualmente". Se siente genial para relajarse.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Ejecute la aplicación artesanal
| ------------------------------------------------- -------------------------
|
| Cuando ejecutamos la aplicación de consola, el comando CLI actual será
| ejecutado en esta consola y la respuesta enviada de vuelta a un terminal
| u otro dispositivo de salida para los desarrolladores. ¡Aquí va nada!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Apagar la aplicación
| ------------------------------------------------- -------------------------
|
| Una vez que Artisan haya terminado de funcionar, activaremos los eventos de cierre
| para que la aplicación pueda realizar cualquier trabajo final antes de cerrar
| abajo el proceso. Esto es lo último que le sucede a la solicitud.
|
*/

$kernel->terminate($input, $status);

exit($status);
